### ISSUE TITLE
[Suggestion] BE Mass Disenchant everything

### ISSUE THREAD

**Issue by BlossomiShymae** [Aluerie/HextechButEfficient#10]
Hi!

I'm a person who doesn't save shards for mastery since I have never upgraded for Champion Mastery 6 or 7. It would be nice to have another script for people like me who want to disenchant every champion shard possible.

I'm interested in making a PR that implements this feature. :>

**Comment by Aluerie** [comment]
Okay, I'm fine with it. 

I didn't think of it because a person can just spam client native Mass Disenchant feature to do it 50 shards at a time.  Well, I guess, it would be nice to be able to do it in one click too.

**Comment by Aluerie** [comment]
Implemented this in c2eca787bae3baf992c2384d51af73b4d2d49ead and 4a56a5d4db33738d86be5db6f2bf12f72e5979ba
