### ISSUE TITLE
[BUG] Skin Collection Stats throws `KeyError: 910001` on run

### ISSUE THREAD

**Issue by BlossomiShymae** [Aluerie/HextechButEfficient#3]
## Describe the bug
The application fails to run Skin Collection Stats with `KeyError: 910001`.

## To Reproduce
Open the application and run Skin Collection Stats.

## Expected behavior
Expected to get stats for skin collection.

## Console
```
HextechButEfficient Console
13:09:18 | Skin Collection Stats |  Starting
13:09:18 | Skin Collection Stats |  Failed with exception. Contact developers about it:
KeyError: 910001
```

## Desktop
 - OS: Windows 10
 - Version: 0.3.0

## Additional context
`910001` seems to be the skin ID for Winterblessed Hwei.

**Comment by Aluerie** [comment]
Thanks, somewhat fixed it in just released 0.4.0 version. 

--- 

I'm using https://cdn.merakianalytics.com/riot/lol/resources/latest/en-US/champions.json to get skin prices, but unfortunately they indeed haven't added Hwei yet. But for example, Winterblessed Camille and other new skins are present in the json. 

It's not allowed to get store related data from the user's league client directly - not allowed as in by rioters, so I have to rely on known public cdns. so I guess gotta wait for meraki to update their stuff. 

As a workaround - added price category 'Unknown' that will be shown in the table with a list of those skins if such problem occurs.  Not sure if I can think of a better solution for this.

![image](https://github.com/Aluerie/HextechButEfficient/assets/33165440/5d3041d2-c847-400e-bfb4-c8a981375e8e)
