### ISSUE TITLE
[BUG] BE Related Loot Mass Opening fails to detect capsules

### ISSUE THREAD

**Issue by BlossomiShymae** [Aluerie/HextechButEfficient#4]
## Describe the bug
The application fails to detect champion and glorious champion capsules in loot inventory.

## To Reproduce
Open the application, have champion capsule or glorious champion capsules, and run BE Related Loot Mass Opening.

## Expected behavior
Expected to detect champion and glorious champion capsules to disenchant.

## Console
```
HextechButEfficient Console
18:20:41 | BE Related Loot Mass Opening |  Starting
18:20:41 | BE Related Loot Mass Opening |  Opened 0 chests
```

## Inventory
![image](https://github.com/Aluerie/HextechButEfficient/assets/87099578/a72df792-7ebb-4efc-a17c-71f623b3afe3)

## Desktop
 - OS: Windows 10
 - Version: 0.4.0

**Comment by Aluerie** [comment]
Thanks again. This should be fixed in newest release. I used wrong commit for convert to exe tool.
